BTC:
    name: BTCUSD
    dataSource:
        type: sim
        key: https://financialmodelingprep.com/api/v3/historical-chart/1min/BTCUSD?apikey=$[fmp.key]
        dataType: url
        indexName: date
        columnFilter:
            - close
            - volume
        period: 1
        dayFirst: False
    feed:
        period: 60
        continuous: False
    libraries:
        - funcs/eventFuncs.py
    actionList:
        closeChange:
            inputCols:
                - close
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: change
            period: 2
        closeUp:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: up
            period: 1
        closeDown:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: down
            period: 1
        emaUp:
            inputCols:
                - closeUp
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28
        emaDown:
            inputCols:
                - closeDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28 
        rs:
            inputCols:
                - emaUp
                - emaDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: divide
            period: 1
        rsi:
            inputCols:
                - rs
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: rsi
            period: 1
        rsi-buy:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: under
            period: 1
            params:
                factor: 20
        rsi-sell:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: over
            period: 1
            params:
                factor: 80
REDDIT:
    name: REDDIT
    dataSource:
        type: func
        setupFunc:
            location: funcs.dataFuncs
            name: setupReddit
        getFunc:
            location: funcs.dataFuncs
            name: redditTest
        period: 10
        params:
            clientId: $[praw.clientId]
            clientSecret: $[praw.clientSecret]
            userAgent: $[praw.userAgent]
            subreddit: pics+videos+askreddit+aww+memes+gaming
    feed:
        period: 60
        continuous: False
        unique: True
    libraries:
        - funcs/dataFuncs.py
    actionList:
        testTrigger:
            inputCols:
                - title
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: testFunc
            period: 1