BTC:
    name: BTCUSD
    dataSource:
        type: stream
        key: https://financialmodelingprep.com/api/v3/quote/BTCUSD?apikey=$[fmp.key]
        dataType: REAL_TIME_REQUEST
        indexName: timestamp
        columnFilter:
            - price
            - volume
        period: 15
        dayFirst: False
    feed:
        period: 60
        continuous: False
    libraries:
        - funcs/eventFuncs.py
    actionList:
        closeChange:
            inputCols:
                - price
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: change
            period: 2
        closeUp:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: up
            period: 1
        closeDown:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: down
            period: 1
        emaUp:
            inputCols:
                - closeUp
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28
        emaDown:
            inputCols:
                - closeDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28 
        rs:
            inputCols:
                - emaUp
                - emaDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: divide
            period: 1
        rsi:
            inputCols:
                - rs
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: rsi
            period: 1
        rsi-buy:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: under
            period: 1
            parameters:
                factor: 20
        rsi-sell:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: over
            period: 1
            parameters:
                factor: 80
REDDIT:
    name: REDDIT
    dataSource:
        type: func
        setupFunc:
            location: funcs.dataFuncs
            name: setupReddit
        getFunc:
            location: funcs.dataFuncs
            name: redditTest
        period: 10
        parameters:
            clientId: $[praw.clientId]
            clientSecret: $[praw.clientSecret]
            userAgent: $[praw.userAgent]
            subreddit: CryptoCurrency+CryptoMarkets+CryptoCurrencyTrading+Bitcoin+BTC+Ethereum+EthTrader+dogecoin
        sequential: True
    feed:
        period: 60
        continuous: False
        unique: True
    libraries:
        - funcs/dataFuncs.py
    actionList:
        testTrigger:
            inputCols:
                - title
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: testFunc
            period: 1
        testEvent:
            inputCols:
                - title
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: testMessageFunc
            period: 1
        wordCountEvent:
            inputCols:
                - comment
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: wordCheck
            period: 1
            parameters:
                word: "the"