block:
    name: AAPL
    libraries:
        - funcs/eventFuncs.py
    dataSource:
        type: dataSim
        key: data/m1test/AAPL.USUSD_Candlestick_1_M_BID_01.04.2020-03.04.2020.csv
        fileType: csv
    feed:
        period: 60
        continuous: False
    actionList:
        closeChange:
            inputCols:
                - close
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: change
            period: 2
        closeUp:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: up
            period: 1
        closeDown:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: down
            period: 1