block:
    name: AAPL
    libraries:
        - funcs/eventFuncs.py
    dataSource:
        type: dataSim
        key: data/m1test/AAPL.USUSD_Candlestick_1_M_BID_01.04.2020-03.04.2020.csv 
        dataType: csv
        index: Local time
        columnFilter:
            - close
            - volume
        period: 1
        constraint:
            lower: '8:30'
            upper: '14:59'
        dayFirst: True
    feed:
        period: 60
        continuous: False
    actionList:
        closeChange:
            inputCols:
                - close
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: change
            period: 2
        closeUp:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: up
            period: 1
        closeDown:
            inputCols:
                - closeChange
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: down
            period: 1
        emaUp:
            inputCols:
                - closeUp
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28
        emaDown:
            inputCols:
                - closeDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 28 
        rs:
            inputCols:
                - emaUp
                - emaDown
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: divide
            period: 1
        rsi:
            inputCols:
                - rs
            actionType: event
            calcFunc:
                location: funcs.eventFuncs
                name: rsi
            period: 1
        rsi-buy:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: under
            period: 1
            params:
                factor: 20
        rsi-sell:
            inputCols:
                - rsi
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: over
            period: 1
            params:
                factor: 80