block:
    name: AAPL
    dataSource:
        type: dataSim
        key: data/m1test/AAPL.USUSD_Candlestick_1_M_BID_01.04.2020-03.04.2020.csv
        fileType: csv
    feed:
        period: 60
        continuous: False
    actionList:
        action1:
            name: lowSearch
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: testFunc
            period: 1
        action2:
            name: RSI
            actionType: event
            dataset:
                inputCol: close
                outputCol: rsi-close
            calcFunc:
                location: funcs.eventFuncs
                name: testFunc
            period: 4
        action3:
            name: change
            actionType: event
            dataset:
                inputCol1: sma-close
            calcFunc:
                location: funcs.eventFuncs
                name: testFunc
            period: 1