block:
    name: AAPL
    libraries:
        - funcs/eventFuncs.py
    dataSource:
        type: stream
        key: xyz
        dataType: real_time
        url: https://financialmodelingprep.com/api/v3/quote/JPYUSD?apikey=988acec08b291b04291918235100cd16
    feed:
        period: 60
        continuous: False
    actionList:
        crossover:
            inputCols:
                - ema7
                - sma28
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: crossover
            period: 2
        ema7:
            actionType: event
            inputCols:
                - price
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 7
        sma28:
            actionType: event
            inputCols:
                - price
            calcFunc:
                location: funcs.eventFuncs
                name: sma
            period: 28