handler1:
    name: firstHandler
    subscriptions:
        - crossover
    calcFunc:
        location: funcs.handlerFuncs
        name: testFunc1
handler2:
    name: handler2
    subscriptions:
        - testTrigger
    calcFunc:
        location: funcs.handlerFuncs
        name: testFunc2