block:
    name: AAPL
    libraries:
        - funcs/eventFuncs.py
    dataSource:
        type: stream
        dataType: real_time_request
        key: https://financialmodelingprep.com/api/v3/quote/JPYUSD?apikey=988acec08b291b04291918235100cd16
        index: timestamp
        columnFilter:
            - price
            - change
        period: 1
    feed:
        period: 60
        continuous: False
    actionList:
        crossover:
            inputCols:
                - ema7
                - sma7
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: crossover
            period: 2
        ema7:
            actionType: event
            inputCols:
                - price
            calcFunc:
                location: funcs.eventFuncs
                name: ema
            period: 7
        sma7:
            actionType: event
            inputCols:
                - price
            calcFunc:
                location: funcs.eventFuncs
                name: sma
            period: 7