block:
    name: AAPL
    dataSource:
        type: dataSim
        key: data/m1test/AAPL.USUSD_Candlestick_1_M_BID_01.04.2020-03.04.2020.csv
        fileType: csv
    feed:
        period: 60
        continuous: False
    actionList:
        lowSearch:
            inputCols:
                - close
            actionType: trigger
            calcFunc:
                location: funcs.triggerFuncs
                name: testFunc
            period: 1
        RSI:
            actionType: event
            inputCols:
                - close
            calcFunc:
                location: funcs.eventFuncs
                name: testFunc
            period: 4
        change2:
            actionType: event
            inputCols:
                - close
            calcFunc:
                location: funcs.eventFuncs
                name: testFunc
            period: 1