handler1:
    name: buyHandler
    subscriptions:
        - rsi-buy
    period: 3
    calcFunc:
        location: funcs.handlerFuncs
        name: containsOneOfEach
    outputFunc:
        location: funcs.handlerFuncs
        name: printOutput